### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by rhatdan** [GrantSeltzer/Manhattan#11]
This is for OCI seccomp not docker.

Needs an explanation of when/where you would use this.

docker run -ti --security-opt secomp;default.json...
runc example.

Show me an example of removing getpwd, and then use the json file to show docker run failing on pwd command.

**Comment by grantseltzer** [comment]
- Added example with docker
- runc doesn't take seccomp configs at cli
- Added resources folder which includes a screenshot of example usage that you described 

:+1:
