### ISSUE TITLE
Abstract library from Docker engine-api

### ISSUE THREAD

**Issue by runcom** [GrantSeltzer/Manhattan#14]
The libraries under parse/ needs to be abstracted from Docker types (specifically the Seccomp) 

This way ocitools can use those libraries as well. 

Ideally the libraries deal only with opencontainers Seccomp types and this tool converts from opencontainers to docker engine-apj

**Comment by grantseltzer** [comment]
Have this done, but I want to rewrite a couple of unit tests to make sure it's working 100%, will have that done tomorrow morning.

**Comment by runcom** [comment]
I think there's no rush take your time :)

**Comment by grantseltzer** [comment]
:+1:  :D
