### ISSUE TITLE
Follow go idioms 

### ISSUE THREAD

**Issue by runcom** [GrantSeltzer/Manhattan#15]
Like consistent variables naming (there are some sneake case which isn't correct) 

This issue aims at grouping all go idioms not respected in this project

**Comment by runcom** [comment]
Another thing, source file naming is sneake case not camel case (files under parse/ are camel case)

**Comment by grantseltzer** [comment]
Fixed both issues you brought up. Let me know if you notice anything else i'm not following.

**Comment by runcom** [comment]
files under tests are sneak_case - pls correct them

**Comment by grantseltzer** [comment]
@runcom I did that after you wrote this: https://github.com/GrantSeltzer/Manhattan/issues/2

What should they be?

**Comment by runcom** [comment]
That's correct, I'm saying file names under tests should follow sneak case as well

**Comment by runcom** [comment]
(In the previous comment I meant files under tests are named camelCase which is wrong)

**Comment by grantseltzer** [comment]
Ah, gotcha. Fixed.
