### ISSUE TITLE
The tool needs to output DOCKER seccomp jsons

### ISSUE THREAD

**Issue by runcom** [GrantSeltzer/Manhattan#26]
there's some confusion probably.

The Manhattan CLI tool has to output Docker seccomp jsons to be used with Docker itself while the library should work with OCI types.
This means there should be a shim layer between the seccomp types and the docker engine-api type in the CLI tool.

**Comment by runcom** [comment]
indeed the example in the README is not working

```
docker run -it --security-opt seccomp:Manhattan.json fedora bash
```

that json is an OCI seccomp json no?

**Comment by runcom** [comment]
NVM it seems it's working, but pls re-test and confirm json files from this tool can be run with docker

**Comment by grantseltzer** [comment]
Looks good: http://i.imgur.com/UglaA70.png

Let me know if you see any other issues, I ran a whole bunch of tests to make sure all the files generated are docker compliant.
