### ISSUE TITLE
constants

### ISSUE THREAD

**Issue by runcom** [GrantSeltzer/Manhattan#29]
use const for dangling strings like https://github.com/GrantSeltzer/Manhattan/blob/master/main.go#L100

**Comment by grantseltzer** [comment]
What exactly do you mean by dangling strings?

**Comment by runcom** [comment]
I mean strings not defined anywhere - the example is a very good candidate because it's not gonna change anytime soon, plus it's repeated in the code and an unlikely change will have you to modify in two places instead of just one in a const declaration

**Comment by grantseltzer** [comment]
Do you think I should this in the main package or the library itself? For example, `""` is used in both main and the library.

**Comment by runcom** [comment]
The empty string it's already a constant, no need to declare that, the meaning is implicit

**Comment by grantseltzer** [comment]
Gotcha, I made the changes to strings that are defined in multiple places

```
    operators := map[string]types.Operator{

        "NE": types.OpNotEqual,

        "LT": types.OpLessThan,

        "LE": types.OpLessEqual,

        "EQ": types.OpEqualTo,

        "GE": types.OpGreaterEqual,

        "GT": types.OpGreaterThan,

        "ME": types.OpMaskedEqual,

    }
```

I didn't want to replace the keys in the maps like this for readability's sake, Let me know if you disagree. Otherwise :+1: :dancer:

**Comment by runcom** [comment]
I'll make a PR to fix that ;)

**Comment by grantseltzer** [comment]
Sounds good

**Comment by runcom** [comment]
the build is broken though:

```
go build -ldflags "-X main.version=0.0.1" -o manhattan
# github.com/grantseltzer/Manhattan/oci-seccomp-gen
oci-seccomp-gen/consts.go:4: constant definition loop
    /home/amurdaca/src/github.com/grantseltzer/Manhattan/oci-seccomp-gen/consts.go:4: overwrite uses overwrite
Makefile:7: recipe for target 'binary' failed
make: *** [binary] Error 2
```

seems like you forgot a constant w/o brackets

**Comment by grantseltzer** [comment]
Woops, Fixed now.

**Comment by runcom** [comment]
this can be closed - but I've opened https://github.com/GrantSeltzer/Manhattan/pull/30

And **remember**, please NEVER EVER push force after you amend a commit to the master branch :) it's going to create lots of troubles to other ppl contributing to your repository :) it's ok to add commits on top :)

**Comment by grantseltzer** [comment]
@runcom What troubles does it create?

**Comment by runcom** [comment]
Like fetch and rebasing are broken

**Comment by runcom** [comment]
http://willi.am/blog/2014/08/12/the-dark-side-of-the-force-push/

**Comment by grantseltzer** [comment]
Oh, that makes sense. Thank you!
