### ISSUE TITLE
parseAction.go

### ISSUE THREAD

**Issue by runcom** [GrantSeltzer/Manhattan#3]
```
 96         fmt.Println("Unrecognized action", action)                              
 97         os.Exit(-3)                                                             
 98         return types.ActKill                                                    
 99     }    
```

return isn't called here

**Comment by grantseltzer** [comment]
Good call  out,  I'm changing the function to return an action and an error. 

the default would read: 
        `return types.ActErrno, errors.New("Unrecognized action" + action)
`

Edit: Is there some type of idiom for what the first return would be? The function is unexported and is only being used by an exported function where I know that the error is being checked so it doesn't matter there. But what about in cases where it is an exported function?

**Comment by grantseltzer** [comment]
Fixed (with fmt.Errorf, not errors.New)
